W-11593638-permission-model-for-sharing-fa
mulesoft/docs-design-center pull request #201
Opened 2022-12-16 00:54 UTC by failup

2022-12-16 17:53 UTC, failup commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +
API Designer team: I think what this doc is missing is another section about the share button and how to add the permissions from there vs from access management. What do you think? ty

2023-01-17 16:46 UTC, lbauret commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +== Design Center Permissions
We may need to add these in a subsection called business group permissions, and add another subsection for project level permissions. Also, we can clarify that whatever higher permission you are granted, that is the one that will be used. (i.e. User with DC Viewer that is project administrator of a certain project, will be able to administrate that project even if he/she is a DC Viewer in the org)

2023-01-17 17:14 UTC, iamerico requested changes

2023-01-17 17:14 UTC, iamerico commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +NOTE: Mule Applications can't be shared.
This NOTE should be posted in the "Sharing Projects from Design Center" section.

2023-01-18 20:06 UTC, lbauret commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +Project Administrator:: Enables users to view, create, and manage all projects within a business group. Use this permission to set up administrators for all the projects within a specific business gr
I would change `Enables users to view, create, and manage all projects within a business group` with `Enables users to manage and share a Design Center project within a business group`

2023-01-19 15:02 UTC, iamerico approved these changes
LGTM

2023-01-19 15:20 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +Design Center Creator:: Enables users to create projects in Design Center from the navigation panel, and view all projects created or shared with the user. Use this permission to invite users to crea
```suggestion
Design Center Creator:: Enables users to create projects in Design Center from the navigation panel, and view all projects created or shared with the user. Use this permission to invite users to create, edit, and maintain your projects.
```

2023-01-19 15:22 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +Design Center Viewer:: Enables users to view all Design Center projects within a business group. Users with this permission cannot create new projects, edit or rename existing projects, or share proj
```suggestion
Design Center Viewer:: Enables users to view all Design Center projects within a business group and test projects with the Mocking Service. Users with this permission cannot create new projects, edit or rename existing projects, or share projects with another user. Assign this permission to those who consume your project in a specific business group.
```

2023-01-19 15:23 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +Project Viewer:: Enables users to view a Design Center project within a business group. Users with this permission cannot create a new project, edit or rename the existing project, or share the proje
```suggestion
Project Viewer:: Enables users to view a Design Center project within a business group and test projects with the Mocking Service. Users with this permission cannot create a new project, edit or rename the existing project, or share the project with another user. Assign this permission to those who consume your project in a specific business group.
```

2023-01-19 15:23 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +Project Editor:: Enables users to edit a Design Center project within a business group. Use this permission to invite users to create, edit and maintain your projects.
```suggestion
Project Editor:: Enables users to edit a Design Center project within a business group. Use this permission to invite users to create, edit, and maintain your projects.
```

2023-01-19 15:25 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +NOTE: If you are granted organization and project permissions, the highest permission level will be the one that applies to that specific project.
```suggestion
NOTE: If you grant organization and project permissions, the highest permission level is the one that applies to that specific project.
```

2023-01-19 15:26 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +NOTE: If you are granted organization and project permissions, the highest permission level will be the one that applies to that specific project.
The previous content is directed at the grantor, not the grantee.

2023-01-19 15:27 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +
Should this list below be a bullet list?

2023-01-19 15:27 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +*Mule flows*: Lists the Mule applications created by you. This view is only available if you have the “Design Center Developer” permission.
```suggestion
*Mule flows*: Lists the Mule applications created by you. This view is available only if you have the Design Center Developer permission.
```

2023-01-19 15:28 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +*Mule flows*: Lists the Mule applications created by you. This view is only available if you have the “Design Center Developer” permission.
I don't think we put permissions in quotes.

2023-01-19 15:28 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +NOTE: Mule Applications can't be shared.
```suggestion
NOTE: Mule applications can't be shared.
```

2023-01-19 15:29 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +You can share your projects and add the corresponding permissions directly from Design Center. To do so:
```suggestion
To share your projects and add the corresponding permissions directly from Design Center:
```

2023-01-19 15:29 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +
This list should be an ordered (numbered) list. Use . instead of *.

2023-01-19 15:30 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +* Go to the Design Center home page and select a project from the list.
```suggestion
* From the Design Center home page, select a project from the list.
```

2023-01-19 19:04 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +NOTE: Mule Applications can't be shared.
(Active voice)

2023-01-19 19:15 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +* On the *API Projects* header, click *Share Project*, or, under project details click *Change access*.
Not sure what you mean by "header". On qax, when I'm in a project, I see a Share button at the top. I don't see Change access. Maybe a screenshot would help?

2023-01-19 19:16 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +** Select the permission level from the dropdown list. The available options are “Viewer”, “Editor” and “Admin”.
```suggestion
** Select the permission level from the dropdown list. The available options are “Viewer”, “Editor”, and “Admin”.
```

2023-01-19 19:17 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +You can share your projects and add the corresponding permissions directly from API Designer. To do so:
```suggestion
To share your projects and add the corresponding permissions directly from API Designer:
```

2023-01-19 19:18 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +* Go to the Design Center home page and select a project from the list.
Do you want to be more specific? Click the project name?

2023-01-19 19:18 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +* Go to the Design Center home page and open a project from your list.
```suggestion
. From the Design Center home page, click the project name.
```

2023-01-19 19:18 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +You can share your projects and add the corresponding permissions directly from API Designer. To do so:
The list below should be numbered, not bulleted.

2023-01-19 19:28 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +* On the header of the project, click *Share*.
```suggestion
* Click the *Share* (picture-of-button) button.
```

2023-01-19 19:30 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +** In the Share project dialog, type the name of the user or the team in your organization you want to give access.
```suggestion
** In the *Share project* dialog box, type the name of the user or the team in your organization you want to give access.
```

2023-01-19 19:31 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +* Open the dropdown list for the user or team that you want to remove access to and click the *Remove Access* option.
```suggestion
. For the user or team that you want to remove access to, select *Remove Access* from the dropdown list.
```

2023-01-19 19:34 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +** In the Share project dialog, type the name of the user or the team in your organization you want to give access.
```suggestion
.. In the *Share project* dialog box, enter the name of the user or the team in your organization to give access.
```

2023-01-19 19:35 UTC, hannanelson commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +** Select the permission level from the dropdown list. The available options are “Viewer”, “Editor” and “Admin”.
```suggestion
.. Select the permission level from the dropdown list. The available options are “Viewer”, “Editor”, and “Admin”.
```

2023-01-20 13:05 UTC, kevintroller approved these changes

2023-01-20 13:09 UTC, merged