W-12725288-github-enable-fa
mulesoft/docs-design-center pull request #210
Opened 2023-03-28 13:37 UTC by failup

2023-03-28 14:24 UTC, iamerico submitted a review, later dismissed
LGTM

2023-03-28 19:19 UTC, carobazan requested changes
Hi Fer, I would add some lines to clarify that if there are sub organizations, org admin user should switch to all Business Groups and enable or disable the Integration as needed for each of them
Also in the WARNING, clarify that if integration is re-enabled, all synchronisations will be lost even when the github repos still exist in GitHub

2023-03-30 15:37 UTC, iamerico approved these changes
LGTM

2023-03-30 16:12 UTC, glenn-rodgers-sf requested changes

2023-03-30 16:12 UTC, glenn-rodgers-sf commented on modules/ROOT/pages/design-ghs-install-authorize.adoc
> +WARNING: This action disables source syncing for all users and projects in your organization. If the integration is re-enabled, all past synchronizations are lost eveb when the repositories still exi
```suggestion
WARNING: This action disables source syncing for all users and projects in your organization. If the integration is re-enabled, all past synchronizations are lost even when the repositories still exist on GitHub.
```

2023-03-30 16:12 UTC, glenn-rodgers-sf commented on modules/ROOT/pages/design-ghs-install-authorize.adoc
> +. Under *Integrations*, disable the Github Integration.
This may be correct, but it is unclear if there is an action in this step. Do they need to click integrations?

2023-03-30 21:29 UTC, merged