W-14181118-ownership-permissions-fa
mulesoft/docs-design-center pull request #218
Opened 2023-12-06 05:10 UTC by failup

2023-12-06 13:10 UTC, iamerico requested changes

2023-12-06 13:10 UTC, iamerico commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +To change the ownership of your projects and add the corresponding permissions directly from Design Center:
This is not a new permission, maybe we could change to:
`To change the ownership of your projects directly from Design Center:`

2023-12-06 13:10 UTC, iamerico commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +.. Select the *Owner* permission level from the dropdown list. .
Maybe we could change to:
`Select the *Transfer Ownership* option from the dropdown list.`

2023-12-06 13:10 UTC, iamerico commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +To change the ownership of your projects and add the corresponding permissions directly from API Designer:
This is not a new permission, maybe we could change to:
`To change the ownership of your projects directly from API Designer:`

2023-12-06 13:10 UTC, iamerico commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +.. In the *Share project* dialog box, enter the name of the user in your organization to give access.
Maybe we could change to:
`In the *Share project* dialog box, enter the name of the user in your organization to give ownership of your project.`

2023-12-06 13:10 UTC, iamerico commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +.. Select the *Owner* permission level from the dropdown list. .
Maybe we could change to:
`Select the *Transfer Ownership* option from the dropdown list.`

2023-12-06 13:20 UTC, lbauret commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +NOTE: This action sends the user an email informing they now own the project.
We are not doing this, so we should remove this line.

2023-12-06 13:20 UTC, lbauret commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +NOTE: This action sends the user an email informing they now own the project.
We shoud also remove this since we are not sending emails when changing ownership

2023-12-06 13:20 UTC, lbauret commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +== Changing Ownership of Projects from Design Center
We should also add that the option to change a project's owner is only available for organization administrators, or the current project owner.

2023-12-07 16:27 UTC, iamerico approved these changes, later dismissed
LGTM

2023-12-07 21:10 UTC, lbauret submitted a review, later dismissed

2023-12-08 13:59 UTC, dmerlob commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +If you are a project owner or an organization administrator you can change the ownership of your projects. To change the ownership of your projects directly from API Designer:
```suggestion
If you are a project owner or an organization administrator, you can change the ownership of your projects. To change the ownership of your projects directly from API Designer:
```

2023-12-08 13:59 UTC, dmerlob commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +If you are a project owner or an organization administrator you can change the ownership of your projects. To change the ownership of your projects directly from Design Center:
```suggestion
If you are a project owner or an organization administrator, you can change the ownership of your projects. To change the ownership of your projects directly from Design Center:
```

2023-12-08 13:59 UTC, dmerlob commented on modules/ROOT/pages/design-assigning-permissions.adoc
> +.. Select *Transfer Ownership*  from the dropdown list.
```suggestion
.. Select *Transfer Ownership* from the dropdown list.
```

2023-12-08 15:46 UTC, dmerlob approved these changes

2023-12-08 15:47 UTC, merged